version: '3.4'
services:
  app:
    container_name: nexswap-backend
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports: 
      - '27017:27017'